"""Lower validated Link register bytecode into standalone Rust native source.

Numerical interpretation remains in the existing VM.  This backend is a
code generator: Link->typed IR->Rust code->rustc (when installed)->native binary.
The emitted Rust code requires no third-party crates.
"""
import shutil
import subprocess
from pathlib import Path
from .syntax import LinkError
from .bridge import verify_links

RUST_LOWERING = {
    'identity': 'Matrix::identity',
    'matrix': 'Matrix::new',
    'phase2': 'Matrix::new (quarter-turn)',
    'adjoint': 'Matrix::adjoint',
    'compose': 'Matrix::compose',
    'add': 'Matrix::binary(add)',
    'sub': 'Matrix::binary(sub)',
}

HEADER = r'''// Generated by linkc. Input matrix rows, output matrix columns.
// Regenerate from .link source: do not modify generated Rust manually.
#[derive(Clone, Copy, Debug)]
struct Complex { re: f64, im: f64 }
impl Complex {
    fn new(re: f64, im: f64) -> Self { Self {re,im} }
    fn conj(self) -> Self { Self::new(self.re, -self.im) }
    fn add(self, rhs: Self) -> Self { Self::new(self.re+rhs.re, self.im+rhs.im) }
    fn sub(self, rhs: Self) -> Self { Self::new(self.re-rhs.re, self.im-rhs.im) }
    fn mul(self, rhs: Self) -> Self {
        Self::new(self.re*rhs.re - self.im*rhs.im, self.re*rhs.im + self.im*rhs.re)
    }
}
#[derive(Clone)]
struct Matrix { rows: usize, cols: usize, data: Vec<Complex> }
impl Matrix {
    fn new(rows: usize, cols: usize, data: Vec<Complex>) -> Self {
        assert_eq!(data.len(), rows*cols); Self {rows,cols,data}
    }
    fn identity(n: usize) -> Self {
        let mut data = vec![Complex::new(0.,0.); n*n];
        for i in 0..n { data[i*n+i] = Complex::new(1.,0.); }
        Self::new(n,n,data)
    }
    fn adjoint(&self) -> Self {
        let mut data = vec![Complex::new(0.,0.); self.rows*self.cols];
        for i in 0..self.rows { for j in 0..self.cols {
            data[j*self.rows+i] = self.data[i*self.cols+j].conj();
        }}
        Self::new(self.cols,self.rows,data)
    }
    // A @ B means A after B. Rows=input, columns=output; numeric order B*A.
    fn compose(a: &Self, b: &Self) -> Self {
        assert_eq!(b.cols,a.rows);
        let mut data = vec![Complex::new(0.,0.); b.rows*a.cols];
        for i in 0..b.rows { for j in 0..a.cols { for k in 0..b.cols {
            let c = b.data[i*b.cols+k].mul(a.data[k*a.cols+j]);
            let idx = i*a.cols+j;
            data[idx] = data[idx].add(c);
        }}}
        Self::new(b.rows,a.cols,data)
    }
    fn binary(a: &Self,b: &Self,subtract: bool) -> Self {
        assert_eq!((a.rows,a.cols),(b.rows,b.cols));
        let data = a.data.iter().zip(b.data.iter()).map(|(x,y)| {
            if subtract {x.sub(*y)} else {x.add(*y)}
        }).collect();
        Self::new(a.rows,a.cols,data)
    }
    fn to_json(&self) -> String {
        let mut out = format!("{{\"shape\":[{},{}],\"matrix\":[",self.rows,self.cols);
        for i in 0..self.rows {
            if i!=0 {out.push(',');} out.push('[');
            for j in 0..self.cols {
                if j!=0 {out.push(',');}
                let z = self.data[i*self.cols+j];
                out.push_str(&format!("{{\"re\":{},\"im\":{}}}",z.re,z.im));
            }
            out.push(']');
        }
        out.push_str("]}"); out
    }
}
'''


def _number(x):
    """Generate Rust float tokens even for integers and negative zero."""
    f = float(x)
    if not (-float('inf') < f < float('inf')):
        raise LinkError('Rust backend requires finite numeric literals')
    return repr(f)


def _validate(program):
    if program.get('format') != 'link-bytecode' or program.get('version') != 1:
        raise LinkError('Rust backend requires Link bytecode version 1')
    if program.get('orientation') != 'input-rows-output-columns':
        raise LinkError('Rust backend requires input-rows-output-columns orientation')
    verify_links(program)
    reg_shapes = []
    for r in program['registers']:
        if r.get('dst') != len(reg_shapes):
            raise LinkError('Rust backend requires sequential register IDs')
        shape = r['shape']
        if len(shape) != 2 or any(type(d) is not int or d <= 0 for d in shape):
            raise LinkError('Invalid Link dimensions')
        op = r['op']
        def ref(key):
            v = r.get(key)
            if type(v) is not int or not (0 <= v < len(reg_shapes)):
                raise LinkError(f'Invalid register reference: {key}')
            return reg_shapes[v]
        if op == 'identity':
            if shape[0] != shape[1]: raise LinkError('Identity must be square')
        elif op == 'matrix':
            values = r['values']
            if len(values) != shape[0] or any(len(row) != shape[1] for row in values):
                raise LinkError('Invalid matrix literal shape')
            if any(len(item)!=2 for row in values for item in row):
                raise LinkError('Invalid complex numeric literal')
        elif op == 'phase2':
            if shape != [1,1] or type(r['q']) is not int or r['q'] not in range(4):
                raise LinkError('Invalid 2bit phase literal')
        elif op == 'adjoint':
            a = ref('arg')
            if shape != [a[1],a[0]]: raise LinkError('Adjoint shape mismatch')
        elif op == 'compose':
            left, right = ref('left'), ref('right')
            if left[0] != right[1] or shape != [right[0],left[1]]:
                raise LinkError('Composition shape mismatch')
        elif op in ('add','sub'):
            left, right = ref('left'), ref('right')
            if left != right or shape != left: raise LinkError('Addition/subtraction shape mismatch')
        else:
            raise LinkError(f'Unsupported Rust opcode {op!r}')
        reg_shapes.append(shape)
    result = program['result']
    if type(result) is not int or not (0 <= result < len(reg_shapes)):
        raise LinkError('Invalid result register')
    if program['result_shape'] != reg_shapes[result]:
        raise LinkError('Incorrect result shape')


def generate_rust(program):
    """Return portable, dependency-free Rust source for optimized typed LIR."""
    _validate(program)
    out = [HEADER, 'fn main() {']
    for r in program['registers']:
        op, idx = r['op'], r['dst']
        symbol = f'r{idx}'
        if 'operator_links' in program:
            edge = program['operator_links'][idx]
            out.append(f'    // Link %{idx}: {edge["source"]} -> {edge["semantic"]} -> {op} -> {RUST_LOWERING[op]}')
        out.append(f'    // Link register %{idx}: {op}, shape={r["shape"]}')
        if op == 'identity':
            expr = f'Matrix::identity({r["shape"][0]})'
        elif op == 'matrix':
            literals = ','.join('Complex::new('+_number(z[0])+','+_number(z[1])+')'
                                 for row in r['values'] for z in row)
            expr = f'Matrix::new({r["shape"][0]},{r["shape"][1]},vec![{literals}])'
        elif op == 'phase2':
            z = [(1,0),(0,1),(-1,0),(0,-1)][r['q']]
            expr = f'Matrix::new(1,1,vec![Complex::new({_number(z[0])},{_number(z[1])})])'
        elif op == 'adjoint':
            expr = f'r{r["arg"]}.adjoint()'
        elif op == 'compose':
            expr = f'Matrix::compose(&r{r["left"]},&r{r["right"]})'
        elif op in ('add','sub'):
            expr = f'Matrix::binary(&r{r["left"]},&r{r["right"]},{str(op=="sub").lower()})'
        out.append(f'    let {symbol} = {expr};')
    out.append(f'    print!("{{}}",r{program["result"]}.to_json());')
    out.append('}')
    return '\n'.join(out)+'\n'


def compile_rust(program, output, *, rustc='rustc', opt_level=2, source_path=None):
    """Write generated Rust and use rustc to create a standalone executable.

    Preserves generated .rs on rustc failure; never claims to emit a binary if
    rustc is unavailable. Any compilation error is raised with rustc stderr.
    """
    output = Path(output)
    if source_path is None:
        source_path = output.with_suffix('.rs')
    source_path = Path(source_path)
    source_path.parent.mkdir(parents=True, exist_ok=True)
    source_path.write_text(generate_rust(program), encoding='utf-8')
    compiler = shutil.which(rustc)
    if compiler is None:
        raise RuntimeError(f'rustc not available: generated Rust source at {source_path}; install Rust and run rustc -O {source_path} -o {output}')
    result = subprocess.run([compiler, str(source_path), '-C', f'opt-level={opt_level}',
                             '-o', str(output)], capture_output=True, text=True)
    if result.returncode:
        raise RuntimeError(f'rustc exited {result.returncode}: {result.stderr}')
    return output
